name: task_manager_apps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  image: ^4.8.0
  flutter_svg_provider: ^1.0.7
  flutter_screenutil: ^5.9.3
  pin_input_text_field: ^4.5.2
  pin_code_fields: ^9.1.0
  pinput: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.10
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/